### ISSUE TITLE
Can't login into account (vk_api error)

### ISSUE THREAD

**Issue by Roma-jpg** [AdrianGuretto/OSINTvk#1]
Не знаю писать на русском или английском так что будет 2 варианта.
Вообщем, хочу использовать инструмент, всё ввожу в правильные поля, но выдаёт такую ошибку: 
```
Traceback (most recent call last):
  File "/home/romeo558/Github/OSINTvk/main.py", line 42, in <module>
    OsintVK(login=login, pwd=pwd, config_path=conf_path)
  File "/home/romeo558/Github/OSINTvk/src/osintVK.py", line 43, in __init__
    session = self._account_login(login, pwd, 51674211)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/romeo558/Github/OSINTvk/src/osintVK.py", line 184, in _account_login
    session.auth(token_only=True)
  File "/usr/local/lib/python3.11/dist-packages/vk_api/vk_api.py", line 185, in auth
    self._auth_token(reauth=reauth)
  File "/usr/local/lib/python3.11/dist-packages/vk_api/vk_api.py", line 237, in _auth_token
    self._api_login()
  File "/usr/local/lib/python3.11/dist-packages/vk_api/vk_api.py", line 516, in _api_login
    raise AuthError('Unknown API auth error')
vk_api.exceptions.AuthError: Unknown API auth error
```

Что самое странное, в аккаунт он пытается войти (приходит уведомление что кто-то вошёл в аккаунт), но появляется ошибка программа завершается. Что не так?

========================

I don't know whether to write in Russian or English so there will be 2 variants.
Anyway, I want to use the tool, I enter everything in the correct fields, but I get this error: 
```
Traceback (most recent call last):
  File "/home/romeo558/Github/OSINTvk/main.py", line 42, in <module>
    OsintVK(login=login, pwd=pwd, config_path=conf_path)
  File "/home/romeo558/Github/OSINTvk/src/osintVK.py", line 43, in __init__
    session = self._account_login(login, pwd, 51674211)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/romeo558/Github/OSINTvk/src/osintVK.py", line 184, in _account_login
    session.auth(token_only=True)
  File "/usr/local/lib/python3.11/dist-packages/vk_api/vk_api.py", line 185, in auth
    self._auth_token(reauth=reauth)
  File "/usr/local/lib/python3.11/dist-packages/vk_api/vk_api.py", line 237, in _auth_token
    self._api_login()
  File "/usr/local/lib/python3.11/dist-packages/vk_api/vk_api.py", line 516, in _api_login
    raise AuthError('Unknown API auth error')
vk_api.exceptions.AuthError: Unknown API auth error
```

What is the strangest thing is that it tries to log in to the account ( I get a notification that someone has logged in to the account), but an error appears and the program terminates. What is wrong?

**Comment by AdrianGuretto** [comment]
Да, известная проблема с API ВКонтакте. Проблема в получении новой сессии через API, когда скрипт создаёт новый файл с информацией о сессии. Работает только с ID сессии, которая была залогинина год назад.
Не было времени пока заняться решением этой проблемы, так как проект держится только на моей инициативе. В ближайшее время планирую исправить все ошибки, но буду рад Вашим, если что-то есть сейчас, что можно предложить.

**Comment by Roma-jpg** [comment]
Да, было бы классно. Возможно я бы и сам что нибудь сделал с кодом, но из редакторов кода на линуксе у меня разве что nano, поэтому не варик. 
Отличная работа, продолжай в том же духе.
